-- begin CUBAPOLIGON_ORDER
alter table CUBAPOLIGON_ORDER add constraint FK_CUBAPOLIGON_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references CUBAPOLIGON_CUSTOMER(ID)^
create index IDX_CUBAPOLIGON_ORDER_ON_CUSTOMER on CUBAPOLIGON_ORDER (CUSTOMER_ID)^
-- end CUBAPOLIGON_ORDER
-- begin CUBAPOLIGON_CUSTOMER
create unique index IDX_CUBAPOLIGON_CUSTOMER_UNIQ_EMAIL on CUBAPOLIGON_CUSTOMER (EMAIL)^
-- end CUBAPOLIGON_CUSTOMER
-- begin CUBAPOLIGON_ORDER_LINE
alter table CUBAPOLIGON_ORDER_LINE add constraint FK_CUBAPOLIGON_ORDER_LINE_ON_PRODUCT foreign key (PRODUCT_ID) references CUBAPOLIGON_PRODUCT(ID)^
alter table CUBAPOLIGON_ORDER_LINE add constraint FK_CUBAPOLIGON_ORDER_LINE_ON_ORDER foreign key (ORDER_ID) references CUBAPOLIGON_ORDER(ID)^
create index IDX_CUBAPOLIGON_ORDER_LINE_ON_PRODUCT on CUBAPOLIGON_ORDER_LINE (PRODUCT_ID)^
create index IDX_CUBAPOLIGON_ORDER_LINE_ON_ORDER on CUBAPOLIGON_ORDER_LINE (ORDER_ID)^
-- end CUBAPOLIGON_ORDER_LINE
