alter table CUBAPOLIGON_ORDER_LINE add constraint FK_CUBAPOLIGON_ORDER_LINE_ON_PRODUCT foreign key (PRODUCT_ID) references CUBAPOLIGON_PRODUCT(ID);
alter table CUBAPOLIGON_ORDER_LINE add constraint FK_CUBAPOLIGON_ORDER_LINE_ON_ORDER foreign key (ORDER_ID) references CUBAPOLIGON_ORDER(ID);
create index IDX_CUBAPOLIGON_ORDER_LINE_ON_PRODUCT on CUBAPOLIGON_ORDER_LINE (PRODUCT_ID);
create index IDX_CUBAPOLIGON_ORDER_LINE_ON_ORDER on CUBAPOLIGON_ORDER_LINE (ORDER_ID);
