alter table CUBAPOLIGON_ORDER add constraint FK_CUBAPOLIGON_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references CUBAPOLIGON_CUSTOMER(ID);
create index IDX_CUBAPOLIGON_ORDER_ON_CUSTOMER on CUBAPOLIGON_ORDER (CUSTOMER_ID);
